import "server-only";

// Remembers which company's sign-in screen a person last used, so they
// can get back to it without the original link.
//
// /login resolves which staff list to show from ?company=<slug> -- there
// is no session at that point to derive it from. That works when someone
// follows the link their shop gave them, and strands them the moment
// they don't: signing out, a session expiring, or a bookmark of bare
// /login all land on "No company specified" with no way forward.
//
// The slug is not a secret. It appears in the sign-in URL every staff
// member already has, and list_active_staff() is callable by anon by
// design (the dropdown has to render before anyone logs in). So a cookie
// holding it grants nothing a typed URL wouldn't -- worst case someone
// edits it and sees a different shop's name dropdown, which is exactly
// what visiting that shop's link would show them anyway. It decides
// which screen renders, never who gets in.
export const LAST_COMPANY_COOKIE = "last_company";

// Long enough to survive a season of not touching the app.
export const LAST_COMPANY_MAX_AGE = 60 * 60 * 24 * 365;

// Slugs are generated by slugify() -- lowercase, digits and dashes only.
// Anything else in that cookie didn't come from us, so don't hand it to
// a database function.
export function isValidSlug(value: string | undefined | null): value is string {
  return typeof value === "string" && /^[a-z0-9-]{1,100}$/.test(value);
}
